[package]
name = "savm-taproot-txs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
rand = "0.8"
hex = "0.4.3"
bitcoin = { version = "0.31.0", features = ["std", "rand-std"] }
